# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: 132252763429.dkr.ecr.us-east-1.amazonaws.com/nanopay/foam-gradle:latest
    working_directory: ~/NANOPAY
    steps:
      - checkout
      - run: mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: git submodule sync
      - run: git submodule update --init

      # Download and cache dependencies
      - restore_cache:
          key: node-v1-{{ checksum "package-lock.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: node-v1-{{ checksum "package-lock.json" }}

      # cache gradle repositories
      - restore_cache:
          keys:
            - gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle" }}
            - gradle-repo-v1-{{ .Branch }}-
            - gradle-repo-v1-

      - run: ./build.sh -ot

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-repo-v1-{{ .Branch }}-{{ checksum "build.gradle" }}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
